name: Deploy Vite Site to Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up Node.js
#        uses: actions/setup-node@v4
#        with:
#          node-version: '22.16.0'
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: Build vite project
#        run: npm run build

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PI_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Install cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -o cloudflared
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/

      - name: Connect and deploy to Raspberry Pi
        run: |
          echo "Connecting via SSH..."
          ssh -o ProxyCommand="cloudflared access ssh --id '${{ secrets.CF_ACCESS_CLIENT_ID }}' --secret '${{ secrets.CF_ACCESS_CLIENT_SECRET }}' --hostname ${{ secrets.PI_HOST }}" \
          -o StrictHostKeyChecking=no \
          "${{ secrets.PI_USER }}@localhost" \
          "echo 'Connected from GitHub!'"

#      - name: Copy build files to Pi
#        run: |
#          scp -r dist/* ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }}:/var/www/portfolio/
#
#      - name: Restart nginx
#        run: |
#          ssh ${{ secrets.PI_USER }}@${{ secrets.PI_HOST }} "sudo systemctl restart nginx"
